# Generated by Django 3.1.2 on 2020-10-15 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birthday',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Honolulu', 'Honolulu'), ('Ewa Beach', 'Ewa Beach'), ('Kailua', 'Kailua'), ('Mililani', 'Mililani'), ('Waianae', 'Waianae'), ('Waipahu', 'Waipahu'), ('Peal City', 'Pearl City'), ('Kapolei', 'Kapolei')], max_length=300, null=True)),
                ('last_updated', models.CharField(choices=[('Less than 12 hrs ago', 'Less than 12 hrs ago'), ('1 day ago', '1 day ago'), ('2 day ago', '2 day ago'), ('3 day ago', '3 day ago'), ('4 day ago', '4 day ago'), ('5 day ago', '5 day ago'), ('6 day ago', '6 day ago'), ('1 week ago', '1 week ago')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('patient', models.ManyToManyField(blank=True, to='maps.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('patients', models.ManyToManyField(blank=True, to='maps.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='thedoctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_doctor', to='maps.doctor'),
        ),
        migrations.AddField(
            model_name='patient',
            name='thelocation',
            field=models.ManyToManyField(related_name='patient_location', to='maps.Location'),
        ),
    ]
