# Generated by Django 3.1.2 on 2020-10-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20201015_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(choices=[('Honolulu', 'Honolulu'), ('Ewa Beach', 'Ewa Beach'), ('Kailua', 'Kailua'), ('Mililani', 'Mililani'), ('Waianae', 'Waianae'), ('Waipahu', 'Waipahu'), ('Peal City', 'Pearl City'), ('Kapolei', 'Kapolei'), ('Kakoako', 'Kakoako')], max_length=300, null=True),
        ),
    ]
