# Generated by Django 3.1.2 on 2020-10-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_location_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='patient',
            field=models.ManyToManyField(blank=True, null=True, to='maps.Patient'),
        ),
    ]
