# Generated by Django 3.1.2 on 2020-10-17 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_auto_20201017_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='patient',
        ),
    ]
