# Generated by Django 3.1.2 on 2020-10-17 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0010_remove_location_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='thepatients',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maps.patient'),
        ),
    ]
