# Generated by Django 3.1.2 on 2020-10-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0011_location_thepatients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='thepatients',
        ),
        migrations.AddField(
            model_name='location',
            name='thepatients',
            field=models.ManyToManyField(to='maps.Patient'),
        ),
    ]
