# Generated by Django 3.1.2 on 2020-10-18 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0012_auto_20201017_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='thepatients',
            new_name='patients',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='thedoctor',
            new_name='doctors',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='thelocation',
        ),
    ]
