# Generated by Django 3.1.2 on 2020-10-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0013_auto_20201018_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='patients',
        ),
        migrations.AddField(
            model_name='patient',
            name='locations',
            field=models.ManyToManyField(related_name='patient_location', to='maps.Location'),
        ),
    ]
