# Generated by Django 3.1.2 on 2020-10-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0014_auto_20201018_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='locations',
            field=models.ManyToManyField(null=True, related_name='patient_location', to='maps.Location'),
        ),
    ]
