# Generated by Django 3.1.2 on 2020-10-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0017_auto_20201018_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='patients',
            field=models.ManyToManyField(blank=True, to='maps.Patient'),
        ),
    ]
