# Generated by Django 3.1.2 on 2020-10-18 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0018_location_patients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='patients',
        ),
        migrations.AddField(
            model_name='location',
            name='patients',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maps.patient'),
        ),
    ]
