# Generated by Django 3.1.2 on 2020-10-19 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0019_auto_20201018_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='patients',
        ),
        migrations.AddField(
            model_name='patient',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maps.location'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='locations',
            field=models.ManyToManyField(related_name='locations', to='maps.Location'),
        ),
    ]
