# Generated by Django 3.1.2 on 2020-10-19 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0020_auto_20201019_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='locations',
        ),
        migrations.AlterField(
            model_name='patient',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_location', to='maps.location'),
        ),
    ]
