# Generated by Django 3.1.2 on 2020-10-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0021_auto_20201019_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='thepatients',
            field=models.ManyToManyField(blank=True, to='maps.Patient'),
        ),
        migrations.AddField(
            model_name='patient',
            name='locations',
            field=models.ManyToManyField(to='maps.Location'),
        ),
    ]
