# Generated by Django 3.1.2 on 2020-10-19 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0023_auto_20201019_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='patients',
        ),
        migrations.AddField(
            model_name='location',
            name='patients',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_location', to='maps.patient'),
        ),
        migrations.RemoveField(
            model_name='patient',
            name='locations',
        ),
        migrations.AddField(
            model_name='patient',
            name='locations',
            field=models.ManyToManyField(blank=True, to='maps.Location'),
        ),
    ]
