# Generated by Django 3.1.2 on 2020-10-19 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0025_auto_20201019_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='patients',
        ),
    ]
