# Generated by Django 3.1.2 on 2020-10-19 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0026_remove_location_patients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='locations',
        ),
        migrations.AddField(
            model_name='location',
            name='patients',
            field=models.ManyToManyField(blank=True, to='maps.Patient'),
        ),
    ]
