# Generated by Django 3.1.2 on 2020-10-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0027_auto_20201019_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='patients',
        ),
        migrations.AddField(
            model_name='patient',
            name='locations',
            field=models.ManyToManyField(blank=True, to='maps.Location'),
        ),
    ]
