# Generated by Django 3.1.2 on 2020-10-19 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0028_auto_20201019_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='locations', to='maps.Location'),
        ),
    ]
