# Generated by Django 3.1.2 on 2020-10-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0029_auto_20201019_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='locations',
            field=models.ManyToManyField(blank=True, to='maps.Location'),
        ),
    ]
