# Generated by Django 3.1.2 on 2020-10-19 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0030_auto_20201019_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='patients',
            field=models.ManyToManyField(blank=True, to='maps.Patient'),
        ),
    ]
