# Generated by Django 3.1.2 on 2020-10-19 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0032_remove_location_patients'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='patients',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maps.patient'),
        ),
    ]
