# Generated by Django 3.1.2 on 2020-10-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0034_remove_location_patients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='locations',
            field=models.ManyToManyField(to='maps.Location'),
        ),
    ]
