# Generated by Django 3.1.2 on 2020-10-20 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0036_location_patients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='patients',
        ),
    ]
