# Generated by Django 3.1.2 on 2020-10-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0037_remove_location_patients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='locations',
        ),
        migrations.AddField(
            model_name='patient',
            name='locations',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
