# Generated by Django 3.1.2 on 2020-10-20 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0038_auto_20201020_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='locations',
        ),
        migrations.AddField(
            model_name='patient',
            name='locations',
            field=models.ManyToManyField(blank=True, to='maps.Location'),
        ),
    ]
