# Generated by Django 3.1.2 on 2020-10-21 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0040_location_patients'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
