# Generated by Django 3.1.2 on 2020-10-23 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0041_patient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='oneLocation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_location', to='maps.location'),
        ),
    ]
