# Generated by Django 3.1.2 on 2020-10-23 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0042_patient_onelocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='oneLocation',
        ),
    ]
