# Generated by Django 3.1.2 on 2020-10-23 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0043_remove_patient_onelocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='patients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maps.patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_doctor', to='maps.doctor'),
        ),
    ]
