# Generated by Django 3.1.2 on 2020-10-23 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0044_auto_20201023_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='patients',
        ),
    ]
