# Generated by Django 3.1.2 on 2020-10-26 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0045_remove_location_patients'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='status',
            field=models.CharField(choices=[('Cleaning', 'Cleaning'), ('Clear', 'Clear')], max_length=300, null=True),
        ),
    ]
