# Generated by Django 3.1.2 on 2020-10-29 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0047_auto_20201027_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Adventist Health Castle', 'Adventist Health Castle'), ('Hawaii State Hospital', 'Hawaii State Hospital'), ('Kahuku Medical Center', 'Kahuku Medical Center'), ('Pali Momi Medical Center', 'Pali Momi Medical Center'), ('The Queens Medical Center-Ewa Beach', 'The Queens Medical Center-Ewa Beach'), ('Wahiawa General Hospital', 'Wahiawa General Hospital'), ('Kaiser Permanente Moanalua Medical Center', 'Kaiser Permanente Moanalua Medical Center'), ('Kapiolani Medical Center for Women & Children', 'Kapiolani Medical Center for Women & Children'), ('Kuakini Medical Center', 'Kuakini Medical Center'), ('The Queens Medical Center', 'The Queens Medical Center'), ('Shriners Hospital for Children', 'Shriners Hospital for Children'), ('Straub Clinic & Hospital', 'Straub Clinic & Hospital'), ('Tripler Army Medical Center', 'Tripler Army Medical Center')], max_length=300, null=True)),
                ('bed_count', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='patients',
        ),
        migrations.RemoveField(
            model_name='location',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='location',
            name='status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='doctors',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='name',
        ),
        migrations.AddField(
            model_name='location',
            name='cooldown',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='loc_type',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Restaurant', 'Restaurant'), ('Bar', 'Bar'), ('Retail', 'Retail'), ('Gym', 'Gym'), ('Industrial', 'Industrial'), ('Business', 'Business')], max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='cooldown',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maps.doctor'),
        ),
        migrations.AddField(
            model_name='patient',
            name='firstname',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='lastname',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maps.hospital'),
        ),
    ]
