# Generated by Django 3.1.2 on 2020-10-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0050_doctor_hospital_location_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='cooldown',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cooldown',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
