# Generated by Django 3.1.2 on 2020-11-27 03:37

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0051_auto_20201030_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='locationfinder',
            field=location_field.models.plain.PlainLocationField(max_length=63, null=True),
        ),
    ]
