# Generated by Django 3.1.2 on 2020-11-27 04:15

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0052_location_locationfinder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200)),
                ('coordinates', location_field.models.plain.PlainLocationField(max_length=63)),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='locationfinder',
        ),
    ]
